spring:
  application:
    name: currency-exchange
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database:
      platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true

server:
  error:
    include-message: always
    include-binding-errors: always

nbp:
  base-url: https://api.nbp.pl/
  api:
    usd-rates: /api/exchangerates/rates/c/usd/?format=json